# Generated by Django 5.0.9 on 2025-07-05 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('recording_file', models.FileField(upload_to='meetings/recordings/', verbose_name='Recording File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Processing Status')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='File Size')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_recordings', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Meeting Recording',
                'verbose_name_plural': 'Meeting Recordings',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField(verbose_name='Summary')),
                ('key_points', models.JSONField(default=list, verbose_name='Key Points')),
                ('action_items', models.JSONField(default=list, verbose_name='Action Items')),
                ('participants', models.JSONField(default=list, verbose_name='Participants')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('ai_model_used', models.CharField(blank=True, max_length=100, verbose_name='AI Model Used')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confidence Score')),
                ('meeting_recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='meetings.meetingrecording', verbose_name='Meeting Recording')),
            ],
            options={
                'verbose_name': 'Meeting Summary',
                'verbose_name_plural': 'Meeting Summaries',
                'ordering': ['-generated_at'],
            },
        ),
    ]
